version: '3.8'
services:
  game-api:
    command: echo "Please use `yarn start game-api` for game-api service"
    restart: 'no'
  db:
    image: postgres:13-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Pa$$w0rd
      POSTGRES_DB: conketkemon
      POSTGRES_HOST_AUTH_METHOD: trust
  db-adminer:
    image: adminer

    restart: always
    ports:
      - 8080:8080
